// Package embedded provides embedded provider configurations.
// This is a stub replacing github.com/charmbracelet/catwalk/pkg/embedded.
package embedded

import "github.com/uglyswap/push/internal/catwalk"

// GetAll returns all embedded providers.
func GetAll() []catwalk.Provider {
	return []catwalk.Provider{
		// Anthropic - Claude models
		{
			ID:                  catwalk.InferenceProviderAnthropic,
			Name:                "Anthropic",
			Type:                catwalk.TypeAnthropic,
			BaseURL:             "https://api.anthropic.com/v1",
			DefaultLargeModelID: "claude-sonnet-4-20250514",
			DefaultSmallModelID: "claude-3-5-haiku-20241022",
			Models: catwalk.ModelList{
				{
					ID:               "claude-opus-4-20250514",
					Name:             "Claude Opus 4",
					CostPer1MIn:      15.0,
					CostPer1MOut:     75.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "claude-sonnet-4-20250514",
					Name:             "Claude Sonnet 4",
					CostPer1MIn:      3.0,
					CostPer1MOut:     15.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "claude-3-7-sonnet-20250219",
					Name:             "Claude 3.7 Sonnet",
					CostPer1MIn:      3.0,
					CostPer1MOut:     15.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "claude-3-5-sonnet-20241022",
					Name:             "Claude 3.5 Sonnet",
					CostPer1MIn:      3.0,
					CostPer1MOut:     15.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "claude-3-5-haiku-20241022",
					Name:             "Claude 3.5 Haiku",
					CostPer1MIn:      0.8,
					CostPer1MOut:     4.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "claude-3-opus-20240229",
					Name:             "Claude 3 Opus",
					CostPer1MIn:      15.0,
					CostPer1MOut:     75.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 4096,
					SupportsImages:   true,
				},
			},
		},
		// OpenAI - GPT and o-series models
		{
			ID:                  catwalk.InferenceProviderOpenAI,
			Name:                "OpenAI",
			Type:                catwalk.TypeOpenAI,
			BaseURL:             "https://api.openai.com/v1",
			DefaultLargeModelID: "gpt-4o",
			DefaultSmallModelID: "gpt-4o-mini",
			Models: catwalk.ModelList{
				{
					ID:               "gpt-4.1",
					Name:             "GPT-4.1",
					CostPer1MIn:      2.0,
					CostPer1MOut:     8.0,
					ContextWindow:    1000000,
					DefaultMaxTokens: 32768,
					SupportsImages:   true,
				},
				{
					ID:               "gpt-4.1-mini",
					Name:             "GPT-4.1 Mini",
					CostPer1MIn:      0.4,
					CostPer1MOut:     1.6,
					ContextWindow:    1000000,
					DefaultMaxTokens: 32768,
					SupportsImages:   true,
				},
				{
					ID:               "gpt-4.1-nano",
					Name:             "GPT-4.1 Nano",
					CostPer1MIn:      0.1,
					CostPer1MOut:     0.4,
					ContextWindow:    1000000,
					DefaultMaxTokens: 32768,
					SupportsImages:   true,
				},
				{
					ID:               "gpt-4o",
					Name:             "GPT-4o",
					CostPer1MIn:      2.5,
					CostPer1MOut:     10.0,
					ContextWindow:    128000,
					DefaultMaxTokens: 16384,
					SupportsImages:   true,
				},
				{
					ID:               "gpt-4o-mini",
					Name:             "GPT-4o Mini",
					CostPer1MIn:      0.15,
					CostPer1MOut:     0.6,
					ContextWindow:    128000,
					DefaultMaxTokens: 16384,
					SupportsImages:   true,
				},
				{
					ID:                     "o3",
					Name:                   "o3",
					CostPer1MIn:            10.0,
					CostPer1MOut:           40.0,
					ContextWindow:          200000,
					DefaultMaxTokens:       100000,
					CanReason:              true,
					ReasoningLevels:        []string{"low", "medium", "high"},
					DefaultReasoningEffort: "medium",
				},
				{
					ID:                     "o3-mini",
					Name:                   "o3 Mini",
					CostPer1MIn:            1.1,
					CostPer1MOut:           4.4,
					ContextWindow:          200000,
					DefaultMaxTokens:       100000,
					CanReason:              true,
					ReasoningLevels:        []string{"low", "medium", "high"},
					DefaultReasoningEffort: "medium",
				},
				{
					ID:                     "o4-mini",
					Name:                   "o4 Mini",
					CostPer1MIn:            1.1,
					CostPer1MOut:           4.4,
					ContextWindow:          200000,
					DefaultMaxTokens:       100000,
					CanReason:              true,
					ReasoningLevels:        []string{"low", "medium", "high"},
					DefaultReasoningEffort: "medium",
				},
				{
					ID:                     "o1",
					Name:                   "o1",
					CostPer1MIn:            15.0,
					CostPer1MOut:           60.0,
					ContextWindow:          200000,
					DefaultMaxTokens:       100000,
					CanReason:              true,
					ReasoningLevels:        []string{"low", "medium", "high"},
					DefaultReasoningEffort: "medium",
				},
				{
					ID:                     "o1-mini",
					Name:                   "o1 Mini",
					CostPer1MIn:            3.0,
					CostPer1MOut:           12.0,
					ContextWindow:          128000,
					DefaultMaxTokens:       65536,
					CanReason:              true,
					ReasoningLevels:        []string{"low", "medium", "high"},
					DefaultReasoningEffort: "medium",
				},
			},
		},
		// Google AI - Gemini models
		{
			ID:                  catwalk.InferenceProviderGoogle,
			Name:                "Google AI",
			Type:                catwalk.TypeGoogle,
			BaseURL:             "https://generativelanguage.googleapis.com/v1beta",
			DefaultLargeModelID: "gemini-2.5-pro-preview-06-05",
			DefaultSmallModelID: "gemini-2.0-flash",
			Models: catwalk.ModelList{
				{
					ID:               "gemini-2.5-pro-preview-06-05",
					Name:             "Gemini 2.5 Pro",
					CostPer1MIn:      1.25,
					CostPer1MOut:     10.0,
					ContextWindow:    1000000,
					DefaultMaxTokens: 65536,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "gemini-2.5-flash-preview-05-20",
					Name:             "Gemini 2.5 Flash",
					CostPer1MIn:      0.15,
					CostPer1MOut:     0.6,
					ContextWindow:    1000000,
					DefaultMaxTokens: 65536,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "gemini-2.0-flash",
					Name:             "Gemini 2.0 Flash",
					CostPer1MIn:      0.1,
					CostPer1MOut:     0.4,
					ContextWindow:    1000000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "gemini-2.0-flash-lite",
					Name:             "Gemini 2.0 Flash Lite",
					CostPer1MIn:      0.075,
					CostPer1MOut:     0.3,
					ContextWindow:    1000000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "gemini-1.5-pro",
					Name:             "Gemini 1.5 Pro",
					CostPer1MIn:      1.25,
					CostPer1MOut:     5.0,
					ContextWindow:    2000000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "gemini-1.5-flash",
					Name:             "Gemini 1.5 Flash",
					CostPer1MIn:      0.075,
					CostPer1MOut:     0.3,
					ContextWindow:    1000000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
			},
		},
		// OpenRouter - Multi-provider gateway
		{
			ID:                  catwalk.InferenceProviderOpenRouter,
			Name:                "OpenRouter",
			Type:                catwalk.TypeOpenRouter,
			BaseURL:             "https://openrouter.ai/api/v1",
			DefaultLargeModelID: "anthropic/claude-sonnet-4",
			DefaultSmallModelID: "anthropic/claude-3.5-haiku",
			Models: catwalk.ModelList{
				// Anthropic via OpenRouter
				{
					ID:               "anthropic/claude-opus-4",
					Name:             "Claude Opus 4",
					CostPer1MIn:      15.0,
					CostPer1MOut:     75.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "anthropic/claude-sonnet-4",
					Name:             "Claude Sonnet 4",
					CostPer1MIn:      3.0,
					CostPer1MOut:     15.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "anthropic/claude-3.5-sonnet",
					Name:             "Claude 3.5 Sonnet",
					CostPer1MIn:      3.0,
					CostPer1MOut:     15.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "anthropic/claude-3.5-haiku",
					Name:             "Claude 3.5 Haiku",
					CostPer1MIn:      0.8,
					CostPer1MOut:     4.0,
					ContextWindow:    200000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				// OpenAI via OpenRouter
				{
					ID:               "openai/gpt-4.1",
					Name:             "GPT-4.1",
					CostPer1MIn:      2.0,
					CostPer1MOut:     8.0,
					ContextWindow:    1000000,
					DefaultMaxTokens: 32768,
					SupportsImages:   true,
				},
				{
					ID:               "openai/gpt-4o",
					Name:             "GPT-4o",
					CostPer1MIn:      2.5,
					CostPer1MOut:     10.0,
					ContextWindow:    128000,
					DefaultMaxTokens: 16384,
					SupportsImages:   true,
				},
				{
					ID:               "openai/o3-mini",
					Name:             "o3 Mini",
					CostPer1MIn:      1.1,
					CostPer1MOut:     4.4,
					ContextWindow:    200000,
					DefaultMaxTokens: 100000,
					CanReason:        true,
				},
				// Google via OpenRouter
				{
					ID:               "google/gemini-2.5-pro-preview",
					Name:             "Gemini 2.5 Pro",
					CostPer1MIn:      1.25,
					CostPer1MOut:     10.0,
					ContextWindow:    1000000,
					DefaultMaxTokens: 65536,
					CanReason:        true,
					SupportsImages:   true,
				},
				{
					ID:               "google/gemini-2.5-flash-preview",
					Name:             "Gemini 2.5 Flash",
					CostPer1MIn:      0.15,
					CostPer1MOut:     0.6,
					ContextWindow:    1000000,
					DefaultMaxTokens: 65536,
					SupportsImages:   true,
				},
				// Meta Llama via OpenRouter
				{
					ID:               "meta-llama/llama-4-maverick",
					Name:             "Llama 4 Maverick",
					CostPer1MIn:      0.2,
					CostPer1MOut:     0.5,
					ContextWindow:    1000000,
					DefaultMaxTokens: 32768,
					SupportsImages:   true,
				},
				{
					ID:               "meta-llama/llama-3.3-70b-instruct",
					Name:             "Llama 3.3 70B",
					CostPer1MIn:      0.3,
					CostPer1MOut:     0.4,
					ContextWindow:    131072,
					DefaultMaxTokens: 8192,
				},
				// DeepSeek via OpenRouter
				{
					ID:               "deepseek/deepseek-r1",
					Name:             "DeepSeek R1",
					CostPer1MIn:      0.55,
					CostPer1MOut:     2.19,
					ContextWindow:    64000,
					DefaultMaxTokens: 8192,
					CanReason:        true,
				},
				{
					ID:               "deepseek/deepseek-chat",
					Name:             "DeepSeek V3",
					CostPer1MIn:      0.27,
					CostPer1MOut:     1.10,
					ContextWindow:    64000,
					DefaultMaxTokens: 8192,
				},
				// Qwen via OpenRouter
				{
					ID:               "qwen/qwen-2.5-72b-instruct",
					Name:             "Qwen 2.5 72B",
					CostPer1MIn:      0.35,
					CostPer1MOut:     0.4,
					ContextWindow:    131072,
					DefaultMaxTokens: 8192,
				},
				{
					ID:               "qwen/qwen-2.5-coder-32b-instruct",
					Name:             "Qwen 2.5 Coder 32B",
					CostPer1MIn:      0.18,
					CostPer1MOut:     0.18,
					ContextWindow:    131072,
					DefaultMaxTokens: 8192,
				},
				// Mistral via OpenRouter
				{
					ID:               "mistralai/mistral-large-2411",
					Name:             "Mistral Large",
					CostPer1MIn:      2.0,
					CostPer1MOut:     6.0,
					ContextWindow:    131072,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				{
					ID:               "mistralai/codestral-2501",
					Name:             "Codestral",
					CostPer1MIn:      0.3,
					CostPer1MOut:     0.9,
					ContextWindow:    256000,
					DefaultMaxTokens: 8192,
				},
			},
		},
		// Zhipu AI (Z.ai) - GLM models (December 2025)
		{
			ID:                  catwalk.InferenceProviderZAI,
			Name:                "Zhipu AI",
			Type:                catwalk.TypeZAI,
			BaseURL:             "https://open.bigmodel.cn/api/paas/v4",
			DefaultLargeModelID: "glm-4.7",
			DefaultSmallModelID: "glm-4-flash-250414",
			Models: catwalk.ModelList{
				// GLM-4.7 - Latest flagship (December 2025)
				{
					ID:               "glm-4.7",
					Name:             "GLM-4.7",
					CostPer1MIn:      0.50,
					CostPer1MOut:     0.50,
					ContextWindow:    202000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
				},
				// GLM-4.6 series (September 2025)
				{
					ID:               "glm-4.6",
					Name:             "GLM-4.6",
					CostPer1MIn:      0.40,
					CostPer1MOut:     0.40,
					ContextWindow:    200000,
					DefaultMaxTokens: 128000,
					CanReason:        true,
				},
				{
					ID:               "glm-4.6v",
					Name:             "GLM-4.6V",
					CostPer1MIn:      0.30,
					CostPer1MOut:     0.90,
					ContextWindow:    128000,
					DefaultMaxTokens: 16384,
					SupportsImages:   true,
				},
				{
					ID:               "glm-4.6v-flash",
					Name:             "GLM-4.6V Flash",
					CostPer1MIn:      0.05,
					CostPer1MOut:     0.15,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				// GLM-4.5 series (July 2025)
				{
					ID:               "glm-4.5",
					Name:             "GLM-4.5",
					CostPer1MIn:      0.30,
					CostPer1MOut:     0.30,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
					CanReason:        true,
				},
				{
					ID:               "glm-4.5-air",
					Name:             "GLM-4.5 Air",
					CostPer1MIn:      0.10,
					CostPer1MOut:     0.10,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
				},
				{
					ID:               "glm-4.5v",
					Name:             "GLM-4.5V",
					CostPer1MIn:      0.25,
					CostPer1MOut:     0.75,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
					SupportsImages:   true,
				},
				// Fast/Flash models
				{
					ID:               "glm-4-flash-250414",
					Name:             "GLM-4 Flash",
					CostPer1MIn:      0.0,
					CostPer1MOut:     0.0,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
				},
				{
					ID:               "glm-4-long",
					Name:             "GLM-4 Long",
					CostPer1MIn:      0.10,
					CostPer1MOut:     0.10,
					ContextWindow:    1000000,
					DefaultMaxTokens: 8192,
				},
				// CodeGeeX for coding
				{
					ID:               "codegeex-4",
					Name:             "CodeGeeX 4",
					CostPer1MIn:      0.0,
					CostPer1MOut:     0.0,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
				},
			},
		},
		// Groq - Ultra-fast LPU inference
		{
			ID:                  catwalk.InferenceProviderGroq,
			Name:                "Groq",
			Type:                catwalk.TypeOpenAICompat,
			BaseURL:             "https://api.groq.com/openai/v1",
			DefaultLargeModelID: "llama-3.3-70b-versatile",
			DefaultSmallModelID: "llama-3.1-8b-instant",
			Models: catwalk.ModelList{
				// Llama 3.3 70B
				{
					ID:               "llama-3.3-70b-versatile",
					Name:             "Llama 3.3 70B Versatile",
					CostPer1MIn:      0.59,
					CostPer1MOut:     0.79,
					ContextWindow:    128000,
					DefaultMaxTokens: 32768,
				},
				{
					ID:               "llama-3.3-70b-specdec",
					Name:             "Llama 3.3 70B SpecDec",
					CostPer1MIn:      0.59,
					CostPer1MOut:     0.99,
					ContextWindow:    8192,
					DefaultMaxTokens: 8192,
				},
				// Llama 3.1 series
				{
					ID:               "llama-3.1-70b-versatile",
					Name:             "Llama 3.1 70B Versatile",
					CostPer1MIn:      0.59,
					CostPer1MOut:     0.79,
					ContextWindow:    128000,
					DefaultMaxTokens: 32768,
				},
				{
					ID:               "llama-3.1-8b-instant",
					Name:             "Llama 3.1 8B Instant",
					CostPer1MIn:      0.05,
					CostPer1MOut:     0.08,
					ContextWindow:    128000,
					DefaultMaxTokens: 8192,
				},
				// Llama 3.2 Vision
				{
					ID:               "llama-3.2-90b-vision-preview",
					Name:             "Llama 3.2 90B Vision",
					CostPer1MIn:      0.90,
					CostPer1MOut:     0.90,
					ContextWindow:    8000,
					DefaultMaxTokens: 8000,
					SupportsImages:   true,
				},
				{
					ID:               "llama-3.2-11b-vision-preview",
					Name:             "Llama 3.2 11B Vision",
					CostPer1MIn:      0.18,
					CostPer1MOut:     0.18,
					ContextWindow:    8000,
					DefaultMaxTokens: 8000,
					SupportsImages:   true,
				},
				// Mixtral
				{
					ID:               "mixtral-8x7b-32768",
					Name:             "Mixtral 8x7B",
					CostPer1MIn:      0.24,
					CostPer1MOut:     0.24,
					ContextWindow:    32768,
					DefaultMaxTokens: 32768,
				},
				// Gemma 2
				{
					ID:               "gemma2-9b-it",
					Name:             "Gemma 2 9B",
					CostPer1MIn:      0.20,
					CostPer1MOut:     0.20,
					ContextWindow:    8192,
					DefaultMaxTokens: 8192,
				},
				// DeepSeek R1 Distill
				{
					ID:               "deepseek-r1-distill-llama-70b",
					Name:             "DeepSeek R1 Distill 70B",
					CostPer1MIn:      0.75,
					CostPer1MOut:     0.99,
					ContextWindow:    128000,
					DefaultMaxTokens: 16384,
					CanReason:        true,
				},
				// Qwen QwQ
				{
					ID:               "qwen-qwq-32b",
					Name:             "Qwen QwQ 32B",
					CostPer1MIn:      0.29,
					CostPer1MOut:     0.39,
					ContextWindow:    32768,
					DefaultMaxTokens: 16384,
					CanReason:        true,
				},
			},
		},
	}
}
